### ISSUE TITLE
The tests for the Song and Post classes pass even if I don't define #self.all.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/ruby-objects-has-many-lab#16]
Hello. As shown in the screenshots below, my code passes the .all tests for Song and Post, despite the fact that I did not make a #self.all method.

![has many objects lab screenshot 1](https://user-images.githubusercontent.com/38870640/45122794-c14abe80-b119-11e8-9cba-d0de92ee36fa.gif)

![has many objects lab screenshot 3](https://user-images.githubusercontent.com/38870640/45122822-d3c4f800-b119-11e8-8ca4-0fb5a4f2a65b.gif)

While there ARE tests for Song.all and Post.all, it appears that they have been written incorrectly. The rspec tests for .all in the Song and Post classes are, respectively: 

describe ".all" do
    it "is a class method that returns an array of all song instances that have been created" do
      expect(Song.class_variable_get(:@@all)).to match([song, song2])
    end
  end

AND

 describe ".all" do
    it "is a class method that returns an array of all post instances that have been created" do
      expect(Post.class_variable_get(:@@all)).to match([post, post2])
    end
  end

I believe the problems are in the calls to #expect. Instead of saying Song.class_variable_get(:@@all) and Post.class_variable_get(:@@all), they need to say Song.all and Post.all, respectively.

As always, thanks for looking into this!

Sdcrouse

**Comment by Sdcrouse** [comment]
I'm not sure why Github keeps auto-correcting :@@all, but that should all be lowercase.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Sdcrouse.

We have updated the tests to specifically require `Song.all` and `Post.all` to exist in order to pass these tests and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
