### ISSUE TITLE
Tests passing when they shouldn't

### ISSUE THREAD

**Issue by regilfillan** [learn-co-curriculum/ruby-objects-has-many-lab#19]
I was able to get tests to pass when my code was actually wrong (upon reviewing with my cohort leader).  Specifically, in the artist.rb file's method called songs, I was able to write 

def songs
@songs = Song.all
end

Which technically got the answer the test wanted, but was not correct.  Same for author.rb and it's posts method. When reviewing, I had left out adding '@songs = []' to my initialize method, which affected the rest of my methods in that i was able to make them cleaner, correct code.

Thanks!

**Comment by maxwellbenton** [comment]
Hi @regilfillan,

Thank you for spotting this and providing feedback. We've updated the tests for this lab so that they specifically check that the test is selecting from `Song.all` rather than using an instance variable on `Artist`. This change has also been applied to the same test in `Author`. This should resolve this issue for students going forward.

Thank you for contributing to a Learn lesson!
